### ISSUE TITLE
腾讯QQ 文字转链接过程中易将“]”包含在链接中

### ISSUE THREAD

**Issue by Z4HD** [jqqqqqqqqqq/coolq-telegram-bot#11]
效果见图

![IMG_20171118_112652.jpg](https://i.loli.net/2017/11/18/5a0fa9c9a948b.jpg)

- 版本：手机QQ 6.6.5

建议使用中文字符中括号“】”以避免QQ文字转链接时生成直接点击会指向错误地址的链接。

**Comment by jqqqqqqqqqq** [comment]
加了个空格

**Comment by Z4HD** [comment]
@jqqqqqqqqqq 老哥忒神速
