### ISSUE TITLE
请问有没有支持「接收语音」的计划？

### ISSUE THREAD

**Issue by seiuneko** [jqqqqqqqqqq/coolq-telegram-bot#14]

**Comment by jqqqqqqqqqq** [comment]
very sooooooon （咕咕咕咕咕）

**Comment by seiuneko** [comment]
好的 谢谢～

**Comment by jqqqqqqqqqq** [comment]
正经回答： GIF 转发和语音消息将会支持，只不过不知道需要多久
GIF 转发可能会在近期先实现，不过将会在3.0版本发布之后
3.0版本更换了底层 API，可能初期会有一些问题需要调整一段时间。。。

**Comment by jqqqqqqqqqq** [comment]
@jqqqqqqqqqq 咦，reply 这个消息还能在 github 发消息么，这么神奇

**Comment by seiuneko** [comment]
哦对了 可以实现@功能喵？

**Comment by jqqqqqqqqqq** [comment]
qq @ telegram 直接打全 id 就行，两边记得空格。

-------

反过来不行，没做这个
。
一般 qq 昵称巨难打，我顶多实现个回复 at 一下。

**Comment by seiuneko** [comment]
嗯 在 tg 下或许可以用命令选单？

**Comment by jqqqqqqqqqq** [comment]
@xyf1219 人少还行，人多效果很不好
