### ISSUE TITLE
建议加入图片上传到图床，也就不用自行开图片服务器了

### ISSUE THREAD

**Issue by stdrc** [jqqqqqqqqqq/coolq-telegram-bot#25]

**Comment by jqqqqqqqqqq** [comment]
考虑过，但是感觉有隐私问题。上传到图床有更大概率被无关人士访问到

**Comment by jqqqqqqqqqq** [comment]
其实本身是可以下完直接发送的，只有 coolq air 需要链接

**Comment by stdrc** [comment]
哦对，隐私确实是个问题，不过感觉可以作为一个可选项，作为没有 pro 的一种妥协方案

**Comment by Z4HD** [comment]
要是有人在群里疯狂斗图的话岂不是瞬间爆破图床？

**Comment by stdrc** [comment]
😂有道理……

**Comment by jqqqqqqqqqq** [comment]
确实可以作为一个选项，不过现在还有一些关键功能没有实现（gif 、视频、文件转发等）

**Comment by jqqqqqqqqqq** [comment]
挤爆图床是个问题，没考虑过这种情况233

**Comment by vipzrx** [comment]
@richardchien   斗图的问题,可以从运营的角度解决. 对接到tg大多是技术群,可以群规说下,只能是报错截图,不能是无关的表情截图

**Comment by jqqqqqqqqqq** [comment]
@vipzrx impossible，我自己就有斗图需求

**Comment by jqqqqqqqqqq** [comment]
而且谁告诉你对接的都是技术群了，我这里对接的全是水群
