### ISSUE TITLE
希望加入联系人互转

### ISSUE THREAD

**Issue by yEs1do** [jqqqqqqqqqq/coolq-telegram-bot#45]
只有群消息互转局限性很大,有没有做成/整合到 [https://github.com/blueset/ehForwarderBot](url) 这样的打算,可以实现对 QQ 联系人的互转消息。

**Comment by jqqqqqqqqqq** [comment]
一开始就没打算做整合，微信封号就封个网页版登录，QQ 一封就全没了，不是不能做，是不打算做。

**Comment by seiuneko** [comment]
@jqqqqqqqqqq 被封号是用户的事（
另外 腾讯封号的依据是什么呢？
coolq？

**Comment by jqqqqqqqqqq** [comment]
修改客户端

**Comment by jqqqqqqqqqq** [comment]
（实际上主要是因为懒
