### ISSUE TITLE
购买了酷Q pro，然而报错，无法转发图片。

### ISSUE THREAD

**Issue by ghost** [jqqqqqqqqqq/coolq-telegram-bot#5]
root@7cf4b961237a:/home/user/coolq/coolq-telegram-bot# python3 daemon.py run
Traceback (most recent call last):
  File "/home/user/coolq/coolq-telegram-bot/cqsdk.py", line 291, in handle
    listener.handler(message)):
  File "/home/user/coolq/coolq-telegram-bot/plugins/qq_namelist.py", line 19, in handle_group_member_list
    with open(os.path.join(CQ_GROUP_LIST_ROOT, message.path.split('\\')[-1]), 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/coolq-data/app/org.dazzyd.cqsocketapi/GroupListCache/1????????.g'
Traceback (most recent call last):
  File "/home/user/coolq/coolq-telegram-bot/cqsdk.py", line 291, in handle
    listener.handler(message)):
  File "/home/user/coolq/coolq-telegram-bot/plugins/qq_namelist.py", line 19, in handle_group_member_list
    with open(os.path.join(CQ_GROUP_LIST_ROOT, message.path.split('\\')[-1]), 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/coolq-data/app/org.dazzyd.cqsocketapi/GroupListCache/5???????????.g'
Update "None" caused error "Conflict: terminated by other long poll or webhook (409)"
Update "None" caused error "Conflict: terminated by other long poll or webhook (409)"

重装了，成功运行酷Q pro  然而报的错误和air时的一样，还是转发不了图片。

**Comment by jqqqqqqqqqq** [comment]
那个啥，你先把常量里的路径改对了再说，很明显你的 coolq 不运行在 '/root/coolq-data/'，而是'/home/user/coolq/'

**Comment by ghost** [comment]
懂了。docker这个参数的锅。-v /root/coolq-data:/home/user/coolq 
群成员昵称正常了。图片还是不能转发。

------------QQ图片可以转发到tg，反过来不行

**Comment by jqqqqqqqqqq** [comment]
qq可以到tg，反过来不行就是我上一个问题里说的，gchat.qpic.cn在海外解析的问题，在国内用国内dns解析一个，然后写到docker的hosts里，注意重启可能会消失

**Comment by jqqqqqqqqqq** [comment]
看起来没动静，先 close 了吧（

**Comment by ghost** [comment]
已解决。建议更改docker的DNS为119.29.29.29更有效。

**Comment by jqqqqqqqqqq** [comment]
可以，我回头测试下，看看要不要写到docker版里边
