### ISSUE TITLE
Code to delete @usernames and links of forwarder messages??

### ISSUE THREAD

**Issue by kraozen** [jqqqqqqqqqq/coolq-telegram-bot#52]
hi i have a telegram forward bot in python and need code to delete of the forward messages all mentions @username and all links http://t.me/........

**Comment by billchenchina** [comment]
Bot API couldn't do this, however.

Try to use an user account to finish this task.

(off topic)

**Comment by jqqqqqqqqqq** [comment]
@kraozen Sorry, I didn't get it. Are you going to remove some content of the original message? Perhaps you could use regular expressions.
