### ISSUE TITLE
转发的消息中机器人自动添加的冒号在 Android Pie 下无法显示

### ISSUE THREAD

**Issue by tnqzh123** [jqqqqqqqqqq/coolq-telegram-bot#56]
如图：
![screenshot_telegram_x_20181117-224600](https://user-images.githubusercontent.com/16630630/48662326-8ff85280-eabb-11e8-803d-78f5feedcdde.png)
![screenshot_tim_20181117-224750](https://user-images.githubusercontent.com/16630630/48662327-91c21600-eabb-11e8-88ef-4cbf1cdaaee7.png)
这个无法显示的冒号的 Unicode 是 `\ua789`，而英文半角冒号的 Unicode 是 `\u003a`，中文全角冒号的 Unicode 是 `\uff1a`。
这个问题仅在类原生的 Android Pie 的 ROM 上出现（国内厂商定制 ROM 没有试过）。Android Pie 好像是改了字体。

**Comment by wtdcode** [comment]
明明是CTB却挂了CTBX的图（逃

**Comment by tnqzh123** [comment]
@wtdcode 因为找不到好头像啦(

**Comment by JogleLew** [comment]
hhhh 我就知道这个冒号迟早要出问题
// CTBX 头像好评

**Comment by jqqqqqqqqqq** [comment]
@tnqzh123 居然还能有这种bug

**Comment by Subilan** [comment]
国内厂商系统字体如果换成 Product Sans（也称 Google Sans）问题依旧，断定是 Product Sans 字体本身的问题。
![a2b53fef-efe5-4418-91e6-b80128af7c39](https://user-images.githubusercontent.com/36447840/48667595-dfb73800-eb14-11e8-9469-d49f60871a6a.png)
然而在 Product Sans 的字符集里没有找到`\ua789`。

**Comment by tnqzh123** [comment]
所以为什么不使用英文半角冒号或者干脆使用中文全角冒号来替代这个奇怪的冒号呢？

**Comment by jqqqqqqqqqq** [comment]
当然是可以的，不过最近没时间写，等12月中以后我改一下

**Comment by Subilan** [comment]
不过我很好奇这样一个冒号是如何打出来的
