### ISSUE TITLE
关键词的功能如何使用

### ISSUE THREAD

**Issue by momo2366** [jqqqqqqqqqq/coolq-telegram-bot#57]
Hi
我看到changelog里面有一条
```
关键词触发改为单条不转发，而不是开启驾驶模式
```
请问这个关键词要如何设置？
Ps:这个功能可不可以设置为触发关键词才转发，比如 hi siri xxxx，触发siri关键字转发这条消息

**Comment by momo2366** [comment]
emmm 看到_002_water_meter_control.md了，私聊管理员来设置
要实现的话，也需要改
plugins/_1006_water_meter_filter.py

**Comment by jqqqqqqqqqq** [comment]
是个想法，如果有时间的话可以做一下

**Comment by jqqqqqqqqqq** [comment]
等我有时间了好好优化一下这个功能，这个功能一直没写进readme是因为写的非常辣鸡

**Comment by jqqqqqqqqqq** [comment]
I'll do some enhancement maybe later this year.
Pull requests are always welcome!
