### ISSUE TITLE
建议加个单向模式

### ISSUE THREAD

**Issue by BH4HPA** [jqqqqqqqqqq/coolq-telegram-bot#66]
我们需要将QQ群的信息自动转发到TG群，但TG群中的消息不自动转发至QQ群
在TG群中的消息只有带上//前缀才会被发送至QQ群

阔以的话可以在群设置中加个布尔选项

**Comment by jqqqqqqqqqq** [comment]
@ENDsoft233 这种需求你可以自己魔改一下，fork一下改一处应该就行

**Comment by BH4HPA** [comment]
@jqqqqqqqqqq 你好，可以指引我一下 // 这一块在哪个文件里吗

**Comment by jqqqqqqqqqq** [comment]
@ENDsoft233 https://github.com/jqqqqqqqqqq/coolq-telegram-bot/blob/8ad466fec8f6738759701f9311e8204c89a9d91b/plugins/_1005_drive_mode.py#L39

**Comment by BH4HPA** [comment]
@jqqqqqqqqqq 成了 谢谢啦~
