### ISSUE TITLE
tg到qq: 无法转发群组中机器人发的消息channel_post

### ISSUE THREAD

**Issue by cesaryuan** [jqqqqqqqqqq/coolq-telegram-bot#68]
- **1.症状描述：**

tg到qq，可以正常转发用户发的消息，但是不能转发机器人发的消息

- **2.python输出**

`
[telegram.bot][DEBUG] (bot.py:59):
Entering: get_updates

[telegram.vendor.ptb_urllib3.urllib3.connectionpool][DEBUG] (connectionpool.py:412):
https://api.telegram.org:443 "POST /bot77777777:XXXXXXXXXXXXXXXXXXXXXXXX
[bot.log](https://github.com/jqqqqqqqqqq/coolq-telegram-bot/files/3807884/bot.log)
XXXXX/getUpdates HTTP/1.1" 200 250

[telegram.bot][DEBUG] (bot.py:1771):
Getting updates: [288726736]

[telegram.bot][DEBUG] (bot.py:61):
[<telegram.update.Update object at 0x7ff41cf44a90>]

[telegram.bot][DEBUG] (bot.py:62):
Exiting: get_updates

[telegram.ext.dispatcher][DEBUG] (dispatcher.py:227):
Processing Update: {'update_id': 288726736, 'channel_post': {'message_id': 49, 'date': 1572941744, 'chat': {'id': -1001179299168, 'type': 'channel', 'title': '测试频道', 'username': 'Cesaryuan_test_channel1'}, 'text': '测试消息', 'entities': [], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False}}

[telegram.ext.dispatcher][DEBUG] (dispatcher.py:284):
Stopping further handlers due to DispatcherHandlerStop

[telegram.bot][DEBUG] (bot.py:59):
Entering: get_updates
`

- **3.部署方式**

docker

- **4.开发分支**

这个不是很懂，就是昨天下载的

**Comment by jqqqqqqqqqq** [comment]
@cesaryuan tg bot 的feature，bot收不到其他bot的消息

**Comment by cesaryuan** [comment]
@jqqqqqqqqqq 机器人的隐私模式默认是开启的，我昨天关了隐私模式之后，通过getupdate测试是可以收到的，下面是我收到的内容

`{
    "ok": true,
    "result": [
        {
            "update_id": 288726743,
            "channel_post": {
                "message_id": 55,
                "chat": {
                    "id": -1001179299168,
                    "title": "测试频道",
                    "username": "Cesaryuan_test_channel1",
                    "type": "channel"
                },
                "date": 1572942973,
                "text": "这是Bot发的消息"
            }
        },
        {
            "update_id": 288726744,
            "message": {
                "message_id": 132,
                "from": {
                    "id": 541004243,
                    "is_bot": false,
                    "first_name": "cesar",
                    "last_name": "yuan",
                    "username": "cesaryuan",
                    "language_code": "zh-hans"
                },
                "chat": {
                    "id": -1001453271784,
                    "title": "测试群组",
                    "username": "cesaryuan_test_group",
                    "type": "supergroup"
                },
                "date": 1572942993,
                "text": "这是用户发的消息"
            }
        }
    ]
}`
![image](https://user-images.githubusercontent.com/35998162/68191505-fcf84700-ffaf-11e9-9b17-b8fda9376c62.png)

**Comment by jqqqqqqqqqq** [comment]
@cesaryuan channel是可以收到的，然而没做channel支持

**Comment by jqqqqqqqqqq** [comment]
@cesaryuan 从来没测试过channel到底能不能正常工作

**Comment by cesaryuan** [comment]
您所说的channel不支持是指不能从channel转发到QQ是吧。
这个我明白，但是我这个不是channel，是group，见截图

![image](https://user-images.githubusercontent.com/35998162/68191726-72fcae00-ffb0-11e9-8c11-5afd1b21c19f.png)

**Comment by jqqqqqqqqqq** [comment]
@cesaryuan https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots

**Comment by cesaryuan** [comment]
我看到这个了，我也不知道为什么我的getupdate可以收到其他bot的消息（我应该没有出现幻觉，测试了好几遍），所以想知道有没有可能自己修改下代码就可以转发bot所发的消息了。
感谢大佬耐心回复。

**Comment by jqqqqqqqqqq** [comment]
@cesaryuan 可以收到其他channel的bot消息，supergroup不行

**Comment by cesaryuan** [comment]
我明白了，我疏忽了个地方，谢谢大佬

**Comment by cesaryuan** [comment]
再问一个问题哈，大佬以后会考虑支持channel吗

**Comment by wtdcode** [comment]
@cesaryuan 目前没空
