### ISSUE TITLE
关于酷Q和windows环境。

### ISSUE THREAD

**Issue by ghost** [jqqqqqqqqqq/coolq-telegram-bot#7]
在docker镜像内运行酷Q发现了很多问题，比如cool运行目录要打开写权限，不然很多酷Q应用会出错。
还有比如wine-qq的镜像对多国语言支持不好等等。
尝试将酷Q在win下运行，所有应用均正常了。
因为发现了酷Q社区，找到了很多有用的应用。比如图灵机器人，小I机器人，翻译，查快递，QQ群内百度

但是在win环境下，配置python环境遇到的困难太多了。各种pip的安装包版本不全等等。

弱弱的建议，可否出个可将酷Q和telegram-bot分离的方案？
比如酷Q运行在家里的软路由上exsi里面的win7虚拟机里，而telegram-bot运行在vps上的docker镜像里。

想法不太成熟，可能表达不太好，见谅。

**Comment by jqqqqqqqqqq** [comment]
可以，但是本项目没有限制你们怎么安装啊，bot 和coolq本来就是分离的，只需要重新编译cqsocketapi那个插件并把监听改成0.0.0.0即可
剩下的地址啥的应该简单改一下就行

只不过，由于需要访问 coolq 的文件才能操作图片转发，所以那部分会因此不可用

**Comment by ghost** [comment]
感谢指点，我再去那边发个issue

**Comment by ghost** [comment]
不能转发图片的话，那看来这么干不行。win环境下运行python过于复杂了，看来暂时无解。

**Comment by jqqqqqqqqqq** [comment]
是的，这也是为啥我推荐放在docker内部而不是外部执行coolq

放在外部也能凑乎用，重新编译 cqsocketsdk，然后把docker的文件目录映射出来
