### ISSUE TITLE
Telegram 转发到 QQ 参数错误 -20

### ISSUE THREAD

**Issue by JasonKhew96** [jqqqqqqqqqq/coolq-telegram-bot#71]
参数错误 -20

UMR日志：
![image](https://user-images.githubusercontent.com/29531167/75014735-f7246400-54c1-11ea-9e16-2d0bd34f0f57.png)

酷q日志：
![image](https://user-images.githubusercontent.com/29531167/75014848-3783e200-54c2-11ea-85a4-114d79cb5498.png)

**Comment by ExerciseBook** [comment]
能不能把那段文本丢这里让网友们一起试试 qwq

**Comment by jqqqqqqqqqq** [comment]
@JasonKhew96 可否复制一下你的昵称，怀疑是emoji的问题

**Comment by JasonKhew96** [comment]
```
Js0n🇲🇾😷
```

**Comment by jqqqqqqqqqq** [comment]
@JasonKhew96 请问你的昵称里有特殊unicode字符吗

**Comment by jqqqqqqqqqq** [comment]
@JasonKhew96 以及请问是所有消息都是这样发送失败吗，可以试试修改一下你的昵称再试一下吗？

**Comment by Coxxs** [comment]
参数错误是因为缺少接收者帐号吧

**Comment by JasonKhew96** [comment]
> @JasonKhew96 请问你的昵称里有特殊unicode字符吗

没有，就那两个emoji
> @JasonKhew96 以及请问是所有消息都是这样发送失败吗，可以试试修改一下你的昵称再试一下吗？

tg去qq全都不行，但是qq去tg没问题。昵称改了，还是有问题。
![image](https://user-images.githubusercontent.com/29531167/75052066-f7485200-5509-11ea-9e2d-21444121a13c.png)
![image](https://user-images.githubusercontent.com/29531167/75052295-50b08100-550a-11ea-92df-b3ef864ee957.png)

难道前几个 commit，config 改了什么特别的东西我还没加进去
我加了那几个 什么Type 的

**Comment by jqqqqqqqqqq** [comment]
我想我知道了，中间某个版本去掉了qq群和group要是负数的逻辑，现在需要加上group type表示群组，然后用正的群号（这就是没有changelog的后果吗

**Comment by JasonKhew96** [comment]
> 我想我知道了，中间某个版本去掉了qq群和group要是负数的逻辑，现在需要加上group type表示群组，然后用正的群号（这就是没有changelog的后果吗

解决了，qq群号移除负数就可以了，感谢。
