### ISSUE TITLE
希望增加多Topology参数的支持

### ISSUE THREAD

**Issue by Saved1387** [jqqqqqqqqqq/coolq-telegram-bot#73]
1.如题
2.后端使用mirai。出现从tg端到QQ端，图片发不出的问题//或者图裂了的问题

mirai-api-http v1.6.3

**Comment by jqqqqqqqqqq** [comment]
1可以考虑，请问具体想要什么样的功能？

2图发不出去和图裂是两种完全不同的问题
发不出去可能是发送端网络问题，等后面mirai带重试的版本发布可能就好了，图裂等一段时间就能加载出来了，图裂表示发送已经成功了，不然应该看不到消息或者看不到裂了的图

**Comment by Saved1387** [comment]
1.emm...就像nginx那个server{}函数能填无数个的样子
2.这个问题比较奇怪，你看图吧
post /sendFriendMessage with data: {'sessionKey': '0Amdyp8P', 'target': 1904403065, 'messageChain': [{'type': 'Image', 'imageId': '/a3bcf2b0-c5ed-4656-8d4b-c2c333540cda', 'url': 'http://c2cpicdw.qpic.cn/offpic_new/0//a3bcf2b0-c5ed-4656-8d4b-c2c333540cda/0'}], 'quote': 64100}
![Screenshot_20200421-234522495](https://user-images.githubusercontent.com/56180468/79928697-38ab9e00-8476-11ea-9f7d-d027887f1862.jpg)
![Screenshot_20200421-232357034](https://user-images.githubusercontent.com/56180468/79928704-3cd7bb80-8476-11ea-859a-3d4fa6954897.jpg)
3.QQ的一些奇怪消息模式会造成UnifiedMessageRelay与后端mirai重连，然后造成另外一些奇怪问题，具体看图
![Screenshot_20200422-065455433](https://user-images.githubusercontent.com/56180468/79928775-77d9ef00-8476-11ea-9fc2-95438c12f9a1.jpg)
![Screenshot_20200422-065446553](https://user-images.githubusercontent.com/56180468/79928804-8b855580-8476-11ea-906b-4c450b0295b5.jpg)
![Screenshot_20200422-065545574](https://user-images.githubusercontent.com/56180468/79928806-8de7af80-8476-11ea-98d9-cbaa5a6a3816.jpg)

**Comment by jqqqqqqqqqq** [comment]
1. Topology是个邻接表表示的有向图，因为没有任何独特属性，所以拥有一个和多个没有任何区别。不过可以考虑扩充定义使得子团的表示更加方便

2. 没看出任何问题，如果你指的是带图的消息根本没有收到的话，建议试试私聊或者换个账号试试

3. 最后一个图看起来是你的目标群组不存在，检查一下配置。群签到那个我正在修

**Comment by Saved1387** [comment]
2.我更多的感觉图裂的情况，问题应该来自于上游mirai
从json反馈回来的结果，这是一个错误的图片地址？
http://c2cpicdw.qpic.cn/offpic_new/0//18446744072377537249-3806766343-9CD1ED5914FFB6E3A6A77E8CA7253235/0
![image](https://user-images.githubusercontent.com/56180468/79942006-61dd2600-8498-11ea-8915-cf7dd5c94f4f.png)

**Comment by jqqqqqqqqqq** [comment]
我找了一个能用的连接看了一下，大概应该是这样
```
http://c2cpicdw.qpic.cn/offpic_new/QQnumber//QQnumber-595229434-265969A98A934DEC3C9237CE99EF32BE/0?term=2
```

建议你去 mamoe/mirai 提这个issue，似乎拿到了一个为0的qq号不知为何
上传图片应该返回一个带有自己qq号的image id，而你的这个情况这个qq号是大小接近 uint64 max 的数字，差距为 1,332,014,367。可能是某个地方搞成负的了？

群签到现在不炸了，请更新 python-mirai-core

**Comment by Saved1387** [comment]
已向mirai-api-http反馈
https://github.com/mamoe/mirai-api-http/issues/67
