### ISSUE TITLE
[help wanted]mirai2tg 无法运行

### ISSUE THREAD

**Issue by qwq233** [jqqqqqqqqqq/coolq-telegram-bot#77]
我想搞个tg群toqq群的机器人转发
但是不知道怎么配置 我配置会报错
日志: https://paste.ubuntu.com/p/Fyk6sg7Zdj/
配置: https://paste.ubuntu.com/p/KRZ4DFZ9WC/
谢谢各位大佬

**Comment by jqqqqqqqqqq** [comment]
安装相关支持请在群里问
